apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scato.fullname" . }}-secrets
  labels:
    {{- include "scato.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if or .Values.postgresql.enabled .Values.externalDatabase.host }}
  database-url: {{ include "scato.databaseUrl" . | quote }}
  {{- end }}
  {{- if .Values.secrets.nvdApiKey }}
  nvd-api-key: {{ .Values.secrets.nvdApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.githubToken }}
  github-token: {{ .Values.secrets.githubToken | quote }}
  {{- end }}
